### PR TITLE
Added TS typings

### PR DESCRIPTION
**Pull request by DavyJohnes**

### CODE REVIEW

**Comment by gurugray** [comment]
Can we move typings to `typings` folder?

PS I updated package.json andt travis config — you need to rebase

**Comment by DavyJohnes** [comment]
> Can we move typings to typings folder?
Done

> PS I updated package.json andt travis config — you need rebase to pass all tests
Done

**Comment by gurugray** [comment]
cool, thank you!!

**Comment by DavyJohnes** [comment]
@gurugray gonna issue new version in npm?

**Comment by gurugray** [comment]
@DavyJohnes already done!

**Pull request merged**
